# Generated by Django 5.2.7 on 2025-11-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0002_rename_certfication_course_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='heard_from',
            field=models.CharField(choices=[('walk in', 'Walk-in'), ('call', 'Call'), ('referral', 'Referral'), ('social media', 'Social Media')], max_length=20),
        ),
    ]
