# Generated by Django 5.2.7 on 2025-11-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0004_rename_eduational_qualification_enquiry_educational_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Date_of_Birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='Guardian_Name',
            new_name='guardian_Name',
        ),
    ]
