# Generated by Django 5.2.7 on 2025-11-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0005_rename_date_of_birth_enquiry_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='guardian_Name',
            new_name='guardian_name',
        ),
    ]
