# Generated by Django 5.2.7 on 2025-11-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0006_rename_guardian_name_enquiry_guardian_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certification',
        ),
    ]
