# Generated by Django 5.2.7 on 2025-11-04 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certfication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certfication_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_syllabus', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('certfication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_app.certfication')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('guardian_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('educational_qualification', models.CharField(max_length=200)),
                ('university_college', models.CharField(max_length=200)),
                ('percentage', models.FloatField()),
                ('year_of_passing', models.IntegerField()),
                ('heard_from', models.CharField(choices=[('walk in', 'Walk-in'), ('call', 'Call'), ('referral', 'Referral'), ('social media', 'Social Media')], default='walk in', max_length=20)),
                ('flexible_timings', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], max_length=10, null=True)),
                ('action', models.CharField(choices=[('follow up', 'Follow Up'), ('admission', 'Admission'), ('not interested', 'Not Interested')], default='follow up', max_length=20)),
                ('course_interested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS_app.course')),
            ],
        ),
    ]
