# Generated by Django 5.2.7 on 2025-11-07 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0002_customuser_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='action',
        ),
    ]
