# Generated by Django 5.2.7 on 2025-11-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0003_alter_enquiry_heard_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='eduational_qualification',
            new_name='educational_qualification',
        ),
    ]
