# Generated by Django 5.2.7 on 2025-11-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0004_alter_enquiry_course_interested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
