# Generated by Django 5.2.7 on 2025-11-07 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0005_alter_enquiry_address_alter_enquiry_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='heard_from',
            field=models.CharField(choices=[('walk in', 'Walk-in'), ('call', 'Call'), ('referral', 'Referral'), ('social media', 'Social Media'), ('website', 'Website')], default='walk in', max_length=20),
        ),
        migrations.CreateModel(
            name='FollowUpAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('action_date', models.DateField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_actions', to='LMS_app.enquiry')),
            ],
        ),
    ]
