# Generated by Django 5.2.7 on 2025-11-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0006_alter_enquiry_heard_from_followupaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUpAction',
        ),
    ]
