# Generated by Django 5.2.7 on 2025-11-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0007_remove_course_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='certfication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certfication_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='course_syllabus',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='action',
            field=models.CharField(choices=[('follow up', 'Follow Up'), ('admission', 'Admission'), ('not interested', 'Not Interested')], default='follow up', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='flexible_timings',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='heard_from',
            field=models.CharField(choices=[('walk in', 'Walk-in'), ('call', 'Call'), ('referral', 'Referral'), ('social media', 'Social Media')], default='walk in', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='certfication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_app.certfication'),
        ),
    ]
