# Generated by Django 5.2.7 on 2025-11-08 04:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0008_followups'),
    ]

    operations = [
        migrations.AddField(
            model_name='followups',
            name='followup_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
