# Generated by Django 5.2.7 on 2025-11-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0009_followups_followup_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUps',
        ),
    ]
