# Generated by Django 5.2.7 on 2025-11-08 05:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0010_delete_followups'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('enquiry_source', models.CharField(editable=False, max_length=20)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('hot_lead', 'Hot Lead'), ('not_interested', 'Not Interested')], default='new', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_actions', to='LMS_app.enquiry')),
            ],
            options={
                'verbose_name_plural': 'Follow Ups',
                'ordering': ['-followup_date'],
            },
        ),
    ]
