# Generated by Django 5.2.7 on 2025-11-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0011_followups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followups',
            name='followup_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
