# Generated by Django 5.1.6 on 2025-11-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0013_remove_followups_remarks_followupremark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUpRemark',
        ),
    ]
