# Generated by Django 5.1.6 on 2025-11-08 10:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0014_delete_followupremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='LMS_app.followups')),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
    ]
