# Generated by Django 5.2.7 on 2025-11-10 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0016_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotInterestedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_interested', 'Not Interested'), ('rejected', 'Rejected'), ('follow_up', 'Follow Up')], default='not_interested', max_length=20)),
                ('archived_on', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_interested_records', to='LMS_app.enquiry')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_interested_lead', to='LMS_app.followups')),
            ],
            options={
                'verbose_name_plural': 'Not Interested Leads',
                'ordering': ['-archived_on'],
            },
        ),
    ]
