# Generated by Django 5.2.7 on 2025-11-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0017_notinterestedlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='notinterestedlead',
            name='last_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
