# Generated by Django 5.2.7 on 2025-11-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0018_notinterestedlead_last_followup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followups',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('hot_lead', 'Hot Lead'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('contacted', 'Contacted'), ('indiscussion', 'In Discussion')], default='new', max_length=20),
        ),
    ]
