# Generated by Django 5.2.7 on 2025-11-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0020_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='module',
            field=models.CharField(blank=True, choices=[('enquiry', 'Enquiry'), ('admission', 'Admission'), ('general', 'General')], max_length=20, null=True),
        ),
    ]
