# Generated by Django 5.2.7 on 2025-11-14 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0023_alter_course_course_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notinterestedlead',
            name='followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='not_interested_lead', to='LMS_app.followups'),
        ),
    ]
