# Generated by Django 5.2.7 on 2025-11-17 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0025_alter_notinterestedlead_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='enquiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='LMS_app.enquiry'),
        ),
    ]
