# Generated by Django 5.2.7 on 2025-11-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0029_alter_admission_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
