# Generated by Django 5.2.7 on 2025-11-18 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0030_admission_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('educational_qualification', models.CharField(max_length=200)),
                ('course_interested', models.CharField(max_length=100)),
                ('heard_from', models.CharField(max_length=20)),
                ('enquiry_date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='website', max_length=20)),
                ('is_converted', models.BooleanField(default=False)),
                ('original_enquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive', to='LMS_app.enquiry')),
            ],
            options={
                'verbose_name_plural': 'Enquiry Archives',
                'ordering': ['-enquiry_date'],
            },
        ),
    ]
