# Generated by Django 5.2.7 on 2025-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0031_enquiryarchive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiryarchive',
            options={'ordering': ['-archived_at'], 'verbose_name_plural': 'Permanent Enquiry Archives'},
        ),
        migrations.RemoveField(
            model_name='enquiryarchive',
            name='is_converted',
        ),
        migrations.RemoveField(
            model_name='enquiryarchive',
            name='original_enquiry',
        ),
        migrations.RemoveField(
            model_name='enquiryarchive',
            name='source',
        ),
        migrations.AddField(
            model_name='enquiryarchive',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryarchive',
            name='final_status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('followup', 'In Follow-up'), ('admitted', 'Admitted'), ('not_interested', 'Not Interested'), ('lost', 'Lost Lead')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='enquiryarchive',
            name='flexible_timings',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enquiryarchive',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiryarchive',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryarchive',
            name='university_college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enquiryarchive',
            name='year_of_passing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryarchive',
            name='course_interested',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryarchive',
            name='educational_qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryarchive',
            name='heard_from',
            field=models.CharField(blank=True, default='walk in', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryarchive',
            name='phone1',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='enquiryarchive',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='enquiryarchive',
            index=models.Index(fields=['phone1'], name='LMS_app_enq_phone1_7eb506_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiryarchive',
            index=models.Index(fields=['student_name'], name='LMS_app_enq_student_ca477b_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiryarchive',
            index=models.Index(fields=['enquiry_date'], name='LMS_app_enq_enquiry_9343db_idx'),
        ),
    ]
