# Generated by Django 5.2.7 on 2025-11-19 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0032_alter_enquiryarchive_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='Enter 12-digit Aadhaar number', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar must be exactly 12 digits')]),
        ),
        migrations.AddField(
            model_name='admission',
            name='class_schedule',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], help_text='Select Online or Offline', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='class_timing',
            field=models.CharField(blank=True, help_text='Select timing based on schedule type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='educational_certificate',
            field=models.FileField(blank=True, help_text='Upload 10th/12th/Degree certificate (PDF/Image)', null=True, upload_to='admissions/certificates/'),
        ),
        migrations.AddField(
            model_name='admission',
            name='payment_structure',
            field=models.CharField(blank=True, choices=[('full', 'Full Payment'), ('installments', 'Installments'), ('emi', 'EMI')], help_text='How student will pay fees', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='student_photo',
            field=models.ImageField(blank=True, help_text='Upload student passport size photo', null=True, upload_to='admissions/photos/'),
        ),
    ]
