# Generated by Django 5.2.7 on 2025-11-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0033_admission_aadhaar_number_admission_class_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='student_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
