# Generated by Django 5.2.7 on 2025-11-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0035_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='interested_in_nactit',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Is student interested in NACTIT exam?', max_length=5),
        ),
        migrations.AddField(
            model_name='admission',
            name='nactit_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='₹1000 added if interested in NACTIT', max_digits=8),
        ),
    ]
