# Generated by Django 5.2.7 on 2025-11-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0036_admission_interested_in_nactit_admission_nactit_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
