# Generated by Django 5.2.7 on 2025-11-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0037_enquiry_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryarchive',
            name='final_status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('followup', 'In Follow-up'), ('admitted', 'Admitted'), ('not_interested', 'Not Interested'), ('lost', 'Lost Lead')], default='new', max_length=30),
        ),
    ]
