# Generated by Django 5.2.7 on 2025-11-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0039_alter_enquiry_heard_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('under review', 'Under Review'), ('confirmed', 'Confirmed'), ('pending', 'Pending'), ('under screening', 'Under Screening')], default='pending', max_length=20),
        ),
    ]
