# Generated by Django 5.2.7 on 2025-11-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0041_alter_enquiry_heard_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='heard_from',
            field=models.CharField(choices=[('walk in', 'Walk-in'), ('call', 'Call'), ('referral', 'Referral'), ('social media', 'Social Media'), ('website', 'Website'), ('news paper', 'news paper'), ('other', 'Other')], default='walk in', max_length=20),
        ),
    ]
