# Generated by Django 5.2.7 on 2025-11-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0044_alter_enquiry_heard_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='heard_from',
            field=models.CharField(choices=[('walk in', 'walk in'), ('call', 'call'), ('referral', 'referral'), ('social media', 'social media'), ('website', 'website'), ('news paper', 'news paper'), ('other', 'other')], default='walk in', max_length=20),
        ),
    ]
