# Generated by Django 5.2.7 on 2025-11-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0045_alter_enquiry_heard_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='interested_in_nactit',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', help_text='Is student interested in NACTIT exam?', max_length=5),
        ),
    ]
