# Generated by Django 5.2.7 on 2025-11-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0046_alter_admission_interested_in_nactit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='interested_in_nactit',
            new_name='interested_in_nactet',
        ),
    ]
