# Generated by Django 5.2.7 on 2025-11-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0047_rename_interested_in_nactit_admission_interested_in_nactet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='nactit_fee',
            new_name='nactet_fee',
        ),
    ]
