# Generated by Django 5.2.7 on 2025-11-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0048_rename_nactit_fee_admission_nactet_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='educational_certificate',
            field=models.FileField(blank=True, help_text='Upload 10th/12th/Degree certificate (PDF/Image)', null=True, upload_to='admissions/certificates'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='student_photo',
            field=models.ImageField(blank=True, help_text='Upload student passport size photo', null=True, upload_to='admissions/photos'),
        ),
    ]
