# Generated by Django 5.2.7 on 2025-11-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0049_alter_admission_educational_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='total_fee_amount',
        ),
    ]
