# Generated by Django 5.2.7 on 2025-11-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0050_rename_amount_payment_total_fee_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='admission_fee',
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
