# Generated by Django 5.2.7 on 2025-11-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0051_remove_payment_admission_fee_admission_admission_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
