# Generated by Django 5.2.7 on 2025-11-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0052_payment_admission_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('print receipt', 'print receipt'), ('email Receipt', 'email Receipt'), ('both', 'both')], default='print receipt', max_length=20),
        ),
    ]
