# Generated by Django 5.2.7 on 2025-11-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0053_alter_payment_options_payment_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_type',
            new_name='receipt_type',
        ),
    ]
