# Generated by Django 5.2.7 on 2025-11-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0054_rename_payment_type_payment_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_type',
            field=models.CharField(choices=[('print receipt', 'print receipt'), ('email receipt', 'email receipt'), ('both', 'both')], default='print receipt', max_length=20),
        ),
    ]
