# Generated by Django 5.2.7 on 2025-11-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0055_alter_payment_receipt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='aadhaar_copy',
            field=models.FileField(blank=True, help_text='Upload Aadhaar card copy (PDF/Image)', null=True, upload_to='admissions/certificates'),
        ),
    ]
