# Generated by Django 5.2.7 on 2025-11-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0056_admission_aadhaar_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='student_photo',
            field=models.ImageField(blank=True, help_text='Upload student passport size photo', null=True, upload_to='admissions/certificates'),
        ),
    ]
