# Generated by Django 5.2.7 on 2025-11-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0057_alter_admission_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='aadhaar_copy',
            field=models.FileField(blank=True, help_text='Upload Aadhaar card copy (PDF/Image)', null=True, upload_to='admissions/certificates/aadhaar'),
        ),
    ]
