# Generated by Django 5.2.7 on 2025-11-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0058_alter_admission_aadhaar_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank transfer', 'bank transfer')], max_length=20),
        ),
    ]
