# Generated by Django 5.2.7 on 2025-11-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0062_alter_payment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'cash'), ('upi', 'upi'), ('card', 'card'), ('bank transfer', 'bank transfer')], max_length=20),
        ),
    ]
