# Generated by Django 5.2.7 on 2025-11-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0063_alter_payment_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='auto_expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
