# Generated by Django 5.2.7 on 2025-12-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0064_notification_auto_expire_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='auto_expire_at',
        ),
    ]
