# Generated by Django 5.2.7 on 2025-12-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0065_remove_notification_auto_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='auto_expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
