# Generated by Django 5.2.7 on 2025-12-01 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0066_notification_auto_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='LMS_app.admission'),
        ),
    ]
