# Generated by Django 5.2.7 on 2025-12-01 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0067_notification_admissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='admissions',
            new_name='admission',
        ),
    ]
