# Generated by Django 5.2.7 on 2025-12-01 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0068_rename_admissions_notification_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='enquiryarchive',
            name='enquiry_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
