# Generated by Django 5.2.7 on 2025-12-01 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0069_alter_admission_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
