# Generated by Django 5.2.7 on 2025-12-02 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0070_alter_enquiry_enquiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='student_name',
            field=models.CharField(help_text='Maximum 100 characters', max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
