# Generated by Django 5.2.7 on 2025-12-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0071_alter_enquiry_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='student_name',
        ),
    ]
