# Generated by Django 5.2.7 on 2025-12-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0072_remove_enquiry_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
