# Generated by Django 5.2.7 on 2025-12-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0073_enquiry_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='payment_structure',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_structure',
            field=models.CharField(blank=True, choices=[('full', 'Full Payment'), ('installments', 'Installments'), ('emi', 'EMI')], help_text='How student will pay fees', max_length=20, null=True),
        ),
    ]
