# Generated by Django 5.2.7 on 2025-12-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0074_remove_admission_payment_structure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_structure',
            field=models.CharField(blank=True, choices=[('full payment', 'full payment'), ('installments', 'installments')], help_text='How student will pay fees', max_length=20, null=True),
        ),
    ]
