# Generated by Django 5.2.7 on 2025-12-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0075_alter_payment_payment_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followups',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('hot_lead', 'Hot Lead'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('contacted', 'Contacted'), ('in_discussion', 'In Discussion')], default='new', max_length=20),
        ),
    ]
