# Generated by Django 5.2.7 on 2025-12-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0076_alter_followups_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_installments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
