# Generated by Django 5.2.7 on 2025-12-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0077_course_number_of_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_structure',
            field=models.CharField(blank=True, choices=[('One time', 'One time'), ('installments', 'installments')], help_text='How student will pay fees', max_length=20, null=True),
        ),
    ]
