# Generated by Django 5.2.7 on 2025-12-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0078_alter_payment_payment_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_structure',
        ),
    ]
