# Generated by Django 5.2.7 on 2025-12-22 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LMS_app', '0078_alter_payment_payment_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_Colloection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elegible_for_discount', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10)),
                ('discount_type', models.CharField(choices=[('refferel', 'refferel'), ('webinar', 'webinar')], max_length=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS_app.payment')),
            ],
        ),
    ]
