# Generated by Django 5.2.7 on 2025-12-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee_Colloection',
        ),
    ]
