# Generated by Django 5.2.7 on 2025-12-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LMS_app', '0078_alter_payment_payment_structure'),
        ('finance_app', '0002_delete_fee_colloection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elegible_for_discount', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10)),
                ('discount_type', models.CharField(choices=[('refferel', 'refferel'), ('webinar', 'webinar'), ('one time', 'one time')], max_length=10)),
                ('webinar_application_timing', models.CharField(blank=True, choices=[('last_2_hours', 'Applied within the last 2 hours'), ('before_4pm', 'Applied before 4 PM the next day')], max_length=20, null=True)),
                ('no_of_refferal', models.IntegerField(default=0)),
                ('refferal_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('installment_number', models.PositiveIntegerField(blank=True, help_text='Which installment is being paid (e.g., 1, 2, 3...)', null=True)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid for this specific installment', max_digits=10, null=True)),
                ('total_fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'cash'), ('upi', 'upi'), ('card', 'card'), ('bank transfer', 'bank transfer')], default='cash', max_length=20)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS_app.payment')),
            ],
        ),
    ]
