# Generated by Django 5.2.7 on 2025-12-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_collection',
            name='total_fee_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
