# Generated by Django 5.2.7 on 2025-12-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_fee_collection_total_fee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_collection',
            name='payment_structure',
            field=models.CharField(blank=True, choices=[('One time', 'One time'), ('installments', 'installments')], help_text='How student will pay fees', max_length=20, null=True),
        ),
    ]
