# Generated by Django 5.2.7 on 2026-01-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0005_fee_collection_payment_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_collection',
            name='qr_code_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
