# Generated by Django 5.2.7 on 2026-01-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0006_fee_collection_qr_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_collection',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', help_text='Payment completion status', max_length=20),
        ),
    ]
