# Generated by Django 5.2.7 on 2026-01-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0007_fee_collection_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_collection',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fee_collection',
            name='razorpay_qr_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
