# Generated by Django 5.2.7 on 2026-01-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0008_fee_collection_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee_collection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fee Collection', 'verbose_name_plural': 'Fee Collections'},
        ),
        migrations.AddField(
            model_name='fee_collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fee_collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
